TRACE_RECORD_JSON_SCHEMA = """
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "root_node": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "There are two types `exec` and `fork`. It donates that how the process launched by its parent"
        },
        "pid": {
          "type": "integer",
          "description": "The process id"
        },
        "filename": {
          "type": "string",
          "description": "The underlying filename of the process"
        },
        "is_bash": {
          "type": "boolean",
          "description": "Whether the process is a bash"
        },
        "file_ops": {
          "type": "array",
          "items": {
              "type": "object",
              "properties": {
                "path": {
                  "type": "string",
                  "description": "The file path"
                },
                "require_read_permission": {
                  "type": "boolean",
                  "description": "Require reading the target file"
                },
                "require_write_permission": {
                  "type": "boolean",
                  "description": "Require writing the target file"
                },
                "require_exec_permission": {
                  "type": "boolean",
                  "description": "Require executing the target file"
                },
                "require_append_permission": {
                  "type": "boolean",
                  "description": "Require appending content to the target"
                }
              }
            },
          "description": "File operations generated by the process"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref" : "#/properties/root_node"
          },
          "description": "Child processes generated by the process"
        }
      },
      "description": "The description of a process"
    },
    "net_ops": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "remote_ip" : {
            "type" : "string",
            "description": "The remote ip addr"
          },
          "remote_port" : {
            "type" : "string",
            "description": "The remote port addr"
          },
          "remote_domain" : {
            "type" : "string",
            "description": "The domain of the remote ip"
          }
        }
      },
      "description": "Network operations generated during the tracing"
    }
  }
}
"""