// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package tracer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type tracingArgsBufferT struct{ Buf [1024]uint8 }

type tracingFileAccessT struct{ LastAccessTgid uint32 }

type tracingFileEvent struct {
	Time         uint64
	Flag         uint32
	Tgid         uint32
	ParentTgid   uint32
	NsTgid       uint32
	NsParentTgid uint32
	Type         uint32
	U            struct{ Buffer [8216]uint8 }
}

type tracingFileIdT struct {
	Inode uint32
	_     [4]byte
	Ctime uint64
}

type tracingFileOpenEvent struct {
	Ctime   uint64
	Dev     uint32
	Inode   uint32
	Syscall uint32
	AccMode uint32
	Path    [4096]uint8
}

type tracingInodeRenameEvent struct {
	Ctime   uint64
	Dev     uint32
	Inode   uint32
	Syscall uint32
	OldPath [4096]uint8
	NewPath [4096]uint8
	_       [4]byte
}

type tracingInodeUnlinkEvent struct {
	Ctime   uint64
	Dev     uint32
	Inode   uint32
	Syscall uint32
	Path    [4096]uint8
	_       [4]byte
}

type tracingNetEventContext struct {
	Time  uint64
	Bytes uint32
}

type tracingPathBufferT struct{ Buf [8192]int8 }

type tracingPathPattern struct{ Prefix [64]uint8 }

type tracingProcessEvent struct {
	Time         uint64
	Flag         uint32
	ParentPid    uint32
	ParentTgid   uint32
	NsParentPid  uint32
	NsParentTgid uint32
	ChildPid     uint32
	ChildTgid    uint32
	NsChildPid   uint32
	NsChildTgid  uint32
	Type         uint32
	U            struct {
		Buffer [5140]uint8
		_      [4]byte
	}
}

type tracingProcessExecEvent struct {
	Syscall  uint32
	Dev      uint32
	Inode    uint32
	_        [4]byte
	Ctime    uint64
	Filepath [4096]uint8
	ArgsArr  [1024]uint8
}

type tracingProcessKillEvent struct {
	Syscall      uint32
	Signal       uint32
	TargetNsTgid uint32
}

type tracingProcessStopPolicyT struct {
	Common uint32
	Buffer [12]uint8
}

type tracingReadlineEvent struct {
	Time         uint64
	Tgid         uint32
	ParentTgid   uint32
	NsTgid       uint32
	NsParentTgid uint32
	TaskComm     [16]uint8
	Readline     [128]uint8
}

type tracingSockaddrIn struct {
	SinFamily uint16
	SinPort   uint16
	SinAddr   struct{ S_addr uint32 }
	Pad       [8]uint8
}

type tracingSockaddrIn6 struct {
	Sin6Family   uint16
	Sin6Port     uint16
	Sin6Flowinfo uint32
	Sin6Addr     struct{ In6U struct{ U6Addr8 [16]uint8 } }
	Sin6ScopeId  uint32
}

type tracingSocketEvent struct {
	Time         uint64
	Flag         uint32
	Tgid         uint32
	ParentTgid   uint32
	NsTgid       uint32
	NsParentTgid uint32
	Type         uint32
	U            struct{ Buffer [28]uint8 }
	_            [4]byte
}

type tracingSyscallCacheT struct {
	Type uint64
	Exec struct{ Args uint64 }
}

type tracingTaskContextT struct{ Type uint64 }

// loadTracing returns the embedded CollectionSpec for tracing.
func loadTracing() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracingBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracing: %w", err)
	}

	return spec, err
}

// loadTracingObjects loads tracing and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracingObjects
//	*tracingPrograms
//	*tracingMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracingObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracing()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracingSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracingSpecs struct {
	tracingProgramSpecs
	tracingMapSpecs
}

// tracingSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracingProgramSpecs struct {
	BashReadlineRet                   *ebpf.ProgramSpec `ebpf:"bash_readline_ret"`
	BpfDnsHandler                     *ebpf.ProgramSpec `ebpf:"bpf_dns_handler"`
	KprobeInetCskAccept               *ebpf.ProgramSpec `ebpf:"kprobe_inet_csk_accept"`
	KprobeSecurityBprmCheck           *ebpf.ProgramSpec `ebpf:"kprobe_security_bprm_check"`
	KprobeSecurityFileOpen            *ebpf.ProgramSpec `ebpf:"kprobe_security_file_open"`
	KprobeSecurityInetConnEstablished *ebpf.ProgramSpec `ebpf:"kprobe_security_inet_conn_established"`
	KprobeSecurityInodeLink           *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_link"`
	KprobeSecurityInodeMkdir          *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_mkdir"`
	KprobeSecurityInodeRename         *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_rename"`
	KprobeSecurityInodeRmdir          *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_rmdir"`
	KprobeSecurityInodeSymlink        *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_symlink"`
	KprobeSecurityInodeUnlink         *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_unlink"`
	KprobeSecuritySkClone             *ebpf.ProgramSpec `ebpf:"kprobe_security_sk_clone"`
	KprobeSecuritySockRcvSkb          *ebpf.ProgramSpec `ebpf:"kprobe_security_sock_rcv_skb"`
	KprobeSecuritySocketAccept        *ebpf.ProgramSpec `ebpf:"kprobe_security_socket_accept"`
	KprobeSecuritySocketConnect       *ebpf.ProgramSpec `ebpf:"kprobe_security_socket_connect"`
	KprobeSecuritySocketListen        *ebpf.ProgramSpec `ebpf:"kprobe_security_socket_listen"`
	KprobeSyscallExecve               *ebpf.ProgramSpec `ebpf:"kprobe_syscall_execve"`
	KprobeSyscallExecveat             *ebpf.ProgramSpec `ebpf:"kprobe_syscall_execveat"`
	TaskKill                          *ebpf.ProgramSpec `ebpf:"task_kill"`
	TracepointRawSyscallsSysExit      *ebpf.ProgramSpec `ebpf:"tracepoint__raw_syscalls__sys_exit"`
	TracepointSchedSchedProcessExec   *ebpf.ProgramSpec `ebpf:"tracepoint__sched__sched_process_exec"`
	TracepointSchedSchedProcessExit   *ebpf.ProgramSpec `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSchedSchedProcessFork   *ebpf.ProgramSpec `ebpf:"tracepoint__sched__sched_process_fork"`
}

// tracingMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracingMapSpecs struct {
	ArgsBuffers             *ebpf.MapSpec `ebpf:"args_buffers"`
	CoreFilePathPatterns    *ebpf.MapSpec `ebpf:"core_file_path_patterns"`
	DnsEvents               *ebpf.MapSpec `ebpf:"dns_events"`
	FileAccessMap           *ebpf.MapSpec `ebpf:"file_access_map"`
	FileEvents              *ebpf.MapSpec `ebpf:"file_events"`
	InterestingPidsMap      *ebpf.MapSpec `ebpf:"interesting_pids_map"`
	MntNsIdList             *ebpf.MapSpec `ebpf:"mnt_ns_id_list"`
	PathBuffers             *ebpf.MapSpec `ebpf:"path_buffers"`
	ProcessEnforcementMap   *ebpf.MapSpec `ebpf:"process_enforcement_map"`
	ProcessEvents           *ebpf.MapSpec `ebpf:"process_events"`
	ProcessExecEventBuffers *ebpf.MapSpec `ebpf:"process_exec_event_buffers"`
	ProcessStopPolicy       *ebpf.MapSpec `ebpf:"process_stop_policy"`
	ProcessTraceLevel       *ebpf.MapSpec `ebpf:"process_trace_level"`
	ReadlineEvents          *ebpf.MapSpec `ebpf:"readline_events"`
	SocketEvents            *ebpf.MapSpec `ebpf:"socket_events"`
	SyscallCache            *ebpf.MapSpec `ebpf:"syscall_cache"`
	TaskContextMap          *ebpf.MapSpec `ebpf:"task_context_map"`
}

// tracingObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracingObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracingObjects struct {
	tracingPrograms
	tracingMaps
}

func (o *tracingObjects) Close() error {
	return _TracingClose(
		&o.tracingPrograms,
		&o.tracingMaps,
	)
}

// tracingMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracingObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracingMaps struct {
	ArgsBuffers             *ebpf.Map `ebpf:"args_buffers"`
	CoreFilePathPatterns    *ebpf.Map `ebpf:"core_file_path_patterns"`
	DnsEvents               *ebpf.Map `ebpf:"dns_events"`
	FileAccessMap           *ebpf.Map `ebpf:"file_access_map"`
	FileEvents              *ebpf.Map `ebpf:"file_events"`
	InterestingPidsMap      *ebpf.Map `ebpf:"interesting_pids_map"`
	MntNsIdList             *ebpf.Map `ebpf:"mnt_ns_id_list"`
	PathBuffers             *ebpf.Map `ebpf:"path_buffers"`
	ProcessEnforcementMap   *ebpf.Map `ebpf:"process_enforcement_map"`
	ProcessEvents           *ebpf.Map `ebpf:"process_events"`
	ProcessExecEventBuffers *ebpf.Map `ebpf:"process_exec_event_buffers"`
	ProcessStopPolicy       *ebpf.Map `ebpf:"process_stop_policy"`
	ProcessTraceLevel       *ebpf.Map `ebpf:"process_trace_level"`
	ReadlineEvents          *ebpf.Map `ebpf:"readline_events"`
	SocketEvents            *ebpf.Map `ebpf:"socket_events"`
	SyscallCache            *ebpf.Map `ebpf:"syscall_cache"`
	TaskContextMap          *ebpf.Map `ebpf:"task_context_map"`
}

func (m *tracingMaps) Close() error {
	return _TracingClose(
		m.ArgsBuffers,
		m.CoreFilePathPatterns,
		m.DnsEvents,
		m.FileAccessMap,
		m.FileEvents,
		m.InterestingPidsMap,
		m.MntNsIdList,
		m.PathBuffers,
		m.ProcessEnforcementMap,
		m.ProcessEvents,
		m.ProcessExecEventBuffers,
		m.ProcessStopPolicy,
		m.ProcessTraceLevel,
		m.ReadlineEvents,
		m.SocketEvents,
		m.SyscallCache,
		m.TaskContextMap,
	)
}

// tracingPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracingObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracingPrograms struct {
	BashReadlineRet                   *ebpf.Program `ebpf:"bash_readline_ret"`
	BpfDnsHandler                     *ebpf.Program `ebpf:"bpf_dns_handler"`
	KprobeInetCskAccept               *ebpf.Program `ebpf:"kprobe_inet_csk_accept"`
	KprobeSecurityBprmCheck           *ebpf.Program `ebpf:"kprobe_security_bprm_check"`
	KprobeSecurityFileOpen            *ebpf.Program `ebpf:"kprobe_security_file_open"`
	KprobeSecurityInetConnEstablished *ebpf.Program `ebpf:"kprobe_security_inet_conn_established"`
	KprobeSecurityInodeLink           *ebpf.Program `ebpf:"kprobe_security_inode_link"`
	KprobeSecurityInodeMkdir          *ebpf.Program `ebpf:"kprobe_security_inode_mkdir"`
	KprobeSecurityInodeRename         *ebpf.Program `ebpf:"kprobe_security_inode_rename"`
	KprobeSecurityInodeRmdir          *ebpf.Program `ebpf:"kprobe_security_inode_rmdir"`
	KprobeSecurityInodeSymlink        *ebpf.Program `ebpf:"kprobe_security_inode_symlink"`
	KprobeSecurityInodeUnlink         *ebpf.Program `ebpf:"kprobe_security_inode_unlink"`
	KprobeSecuritySkClone             *ebpf.Program `ebpf:"kprobe_security_sk_clone"`
	KprobeSecuritySockRcvSkb          *ebpf.Program `ebpf:"kprobe_security_sock_rcv_skb"`
	KprobeSecuritySocketAccept        *ebpf.Program `ebpf:"kprobe_security_socket_accept"`
	KprobeSecuritySocketConnect       *ebpf.Program `ebpf:"kprobe_security_socket_connect"`
	KprobeSecuritySocketListen        *ebpf.Program `ebpf:"kprobe_security_socket_listen"`
	KprobeSyscallExecve               *ebpf.Program `ebpf:"kprobe_syscall_execve"`
	KprobeSyscallExecveat             *ebpf.Program `ebpf:"kprobe_syscall_execveat"`
	TaskKill                          *ebpf.Program `ebpf:"task_kill"`
	TracepointRawSyscallsSysExit      *ebpf.Program `ebpf:"tracepoint__raw_syscalls__sys_exit"`
	TracepointSchedSchedProcessExec   *ebpf.Program `ebpf:"tracepoint__sched__sched_process_exec"`
	TracepointSchedSchedProcessExit   *ebpf.Program `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSchedSchedProcessFork   *ebpf.Program `ebpf:"tracepoint__sched__sched_process_fork"`
}

func (p *tracingPrograms) Close() error {
	return _TracingClose(
		p.BashReadlineRet,
		p.BpfDnsHandler,
		p.KprobeInetCskAccept,
		p.KprobeSecurityBprmCheck,
		p.KprobeSecurityFileOpen,
		p.KprobeSecurityInetConnEstablished,
		p.KprobeSecurityInodeLink,
		p.KprobeSecurityInodeMkdir,
		p.KprobeSecurityInodeRename,
		p.KprobeSecurityInodeRmdir,
		p.KprobeSecurityInodeSymlink,
		p.KprobeSecurityInodeUnlink,
		p.KprobeSecuritySkClone,
		p.KprobeSecuritySockRcvSkb,
		p.KprobeSecuritySocketAccept,
		p.KprobeSecuritySocketConnect,
		p.KprobeSecuritySocketListen,
		p.KprobeSyscallExecve,
		p.KprobeSyscallExecveat,
		p.TaskKill,
		p.TracepointRawSyscallsSysExit,
		p.TracepointSchedSchedProcessExec,
		p.TracepointSchedSchedProcessExit,
		p.TracepointSchedSchedProcessFork,
	)
}

func _TracingClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracing_x86_bpfel.o
var _TracingBytes []byte
